import { mkdtemp } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import fs from "fs-extra";
import { x } from "tinyexec";

export async function createProjectFixture(options = {}) {
  const {
    name = "fixture-project",
    version = "1.0.0",
    type = "module",
    withCliff = true,
    remote = true,
  } = options;

  const cwd = await mkdtemp(path.join(os.tmpdir(), "releaseasy-integration-"));

  await fs.outputJson(
    path.join(cwd, "package.json"),
    {
      name,
      version,
      type,
      packageManager: "npm@11.0.0",
    },
    {
      spaces: 2,
    },
  );

  // Git 仓库
  await git(cwd, ["init", "-b", "main"]);

  await git(cwd, ["config", "user.name", "Releaseasy Test"]);
  await git(cwd, ["config", "user.email", "releaseasy@test.local"]);

  // git-cliff 配置
  if (withCliff) {
    await fs.writeFile(
      path.join(cwd, "cliff.toml"),
      `
[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""

body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}

{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}])
{% endfor %}
{% endfor %}
"""

footer = """
<!-- generated by releaseasy integration test -->
"""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
`,
      "utf8",
    );
  }

  // 第一条 commit
  await git(cwd, ["add", "."]);
  await git(cwd, ["commit", "-m", "chore: initial commit"]);

  if (remote) {
    await git(cwd, ["remote", "add", "origin", "https://github.com/example/releaseasy-test.git"]);
  }

  return cwd;
}

export async function git(cwd, args, options = {}) {
  return x("git", args, {
    throwOnError: true,
    nodeOptions: {
      cwd,
      stdio: options.stdio ?? "pipe",
    },
  });
}

export async function readPackage(cwd) {
  return fs.readJson(path.join(cwd, "package.json"));
}

export async function readFile(cwd, filename) {
  return fs.readFile(path.join(cwd, filename), "utf8");
}

export async function gitLog(cwd) {
  const result = await git(cwd, ["log", "-1", "--pretty=%H%n%s"]);

  const [sha, message] = result.stdout.trim().split("\n");

  return {
    sha,
    message,
  };
}

export async function gitTags(cwd) {
  const result = await git(cwd, ["tag", "--list"]);

  return result.stdout.trim().split("\n").filter(Boolean);
}

export async function gitStatus(cwd) {
  const result = await git(cwd, ["status", "--porcelain"]);

  return result.stdout.trim();
}

export async function cleanupProject(cwd) {
  await fs.remove(cwd);
}
