name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # 使能够发布GitHub版本
  id-token: write # OIDC 发布所必须的

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --no-git-checks

      - name: Generate changelog for the latest release
        run: pnpm releaseasy changelog --config cliff.toml -o CHANGELOG-LATEST.md -vv --latest --strip header

      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG-LATEST.md
          prerelease: ${{ contains(github.ref_name, '-') }}
